import { createThemedStyles, themed } from '@/hooks/create-themed-styles';

export const useDashboardStyles = createThemedStyles((colors, isDark) => ({
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.bg,
    gap: 12,
    padding: 24,
  },
  muted: { color: colors.muted, fontSize: 14 },
  scroll: { flex: 1, backgroundColor: colors.bg },
  content: { paddingBottom: 36 },
  errBox: {
    margin: 16,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    ...themed.errorBox(isDark),
  },
  errText: { ...themed.errorText(isDark), fontSize: 14 },
  heroWrap: { padding: 16, paddingBottom: 0 },
  banner: {
    margin: 16,
    padding: 20,
    borderRadius: 24,
  },
  heroTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    alignItems: 'flex-start',
  },
  greeting: { color: 'rgba(255,255,255,0.82)', fontSize: 13, fontWeight: '700' },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarLarge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: '#fff', fontSize: 20, fontWeight: '900' },
  avText: { fontSize: 22, fontWeight: '700' },
  bannerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#fff',
    marginBottom: 4,
  },
  bannerSub: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.9)',
    marginBottom: 12,
  },
  heroMeta: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  dateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  dateText: { fontSize: 12, color: '#fff', fontWeight: '600' },
  stats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  statsWide: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 12,
    gap: 12,
  },
  statCard: {
    flex: 1,
    minWidth: '45%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    padding: 14,
    borderRadius: 16,
  },
  statCardGrid: {
    width: '47%',
    flexGrow: 1,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 20,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  statIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statIconLarge: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statN: { fontSize: 18, fontWeight: '700', color: colors.text },
  statL: { fontSize: 12, color: colors.muted },
  quickActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingHorizontal: 16,
    marginBottom: 14,
  },
  actionCard: {
    flex: 1,
    minWidth: '30%',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 12,
    gap: 8,
  },
  actionIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.text,
    textAlign: 'center',
  },
  panel: {
    marginHorizontal: 16,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
  },
  panelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  panelHint: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  glanceRow: { gap: 10 },
  glanceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    borderRadius: 14,
    ...themed.subtleSurface(colors, isDark),
  },
  glanceLabel: { fontSize: 12, color: colors.muted, fontWeight: '700' },
  glanceValue: { fontSize: 15, color: colors.text, fontWeight: '800', maxWidth: 240 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 4,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 10,
  },
  sectionAction: { fontSize: 13, fontWeight: '800' },
  empty: {
    paddingHorizontal: 24,
    color: colors.muted,
    fontSize: 14,
    marginBottom: 12,
    marginHorizontal: 20,
  },
  scheduleCard: {
    flexDirection: 'row',
    gap: 12,
    marginHorizontal: 16,
    marginBottom: 10,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
  },
  timeIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scheduleBody: { flex: 1 },
  feesCard: {
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 16,
    padding: 18,
    borderRadius: 20,
    backgroundColor: isDark ? '#064E3B' : '#ECFDF5',
    borderColor: isDark ? '#065F46' : '#A7F3D0',
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  feesLabel: { fontSize: 13, fontWeight: '800', color: isDark ? '#6EE7B7' : '#047857' },
  feesValue: { fontSize: 24, fontWeight: '900', color: colors.text, marginTop: 2 },
  feesMeta: { fontSize: 12, color: isDark ? '#6EE7B7' : '#047857', marginTop: 2 },
  smallButton: {
    backgroundColor: isDark ? '#059669' : '#047857',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  smallButtonText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  card: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginBottom: 10,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    overflow: 'hidden',
  },
  cardAccent: { width: 4 },
  cardBody: { flex: 1, padding: 14 },
  cardTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 4,
  },
  cardMeta: { fontSize: 12, color: colors.muted, marginBottom: 8 },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  due: { fontSize: 12, color: colors.muted },
  badge: {
    backgroundColor: isDark ? '#78350F' : '#FEF3C7',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeDone: { backgroundColor: isDark ? '#065F46' : '#D1FAE5' },
  badgeText: { fontSize: 11, fontWeight: '700', color: colors.text },
  classCard: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 20,
    overflow: 'hidden',
    flexDirection: 'row',
  },
  classAccent: { width: 4 },
  classBody: { flex: 1, padding: 14 },
  className: { fontSize: 16, fontWeight: '700', color: colors.text, marginBottom: 4 },
  classMeta: { fontSize: 12, color: colors.muted },
  taskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginHorizontal: 20,
    marginBottom: 10,
  },
  taskText: { fontSize: 14, color: colors.text },
  emptyBox: {
    marginHorizontal: 16,
    padding: 24,
    borderRadius: 20,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    alignItems: 'center',
    gap: 8,
  },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: colors.text },
  emptyText: { fontSize: 13, color: colors.muted, textAlign: 'center' },
  childCard: {
    marginHorizontal: 16,
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    padding: 16,
    borderRadius: 20,
  },
  childName: { fontSize: 16, fontWeight: '700', color: colors.text },
  childMeta: { fontSize: 12, color: colors.muted, marginTop: 2 },
  actions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  actionPill: {
    backgroundColor: colors.card,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  actionPillText: { fontSize: 13, fontWeight: '500', color: colors.text },
}));
