import { createThemedStyles, themed } from '@/hooks/create-themed-styles';

/** Common screen styles for student/teacher/parent portal pages */
export const usePortalScreenStyles = createThemedStyles((colors, isDark) => ({
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.bg,
    gap: 12,
    padding: 24,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.bg,
  },
  scroll: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  contentWide: {
    paddingBottom: 36,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.text,
  },
  sub: {
    fontSize: 14,
    color: colors.muted,
    marginBottom: 16,
  },
  sectionHeading: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 12,
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
  },
  muted: {
    color: colors.muted,
    fontSize: 14,
  },
  body: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.text,
  },
  label: {
    fontSize: 12,
    color: colors.muted,
    fontWeight: '700',
  },
  err: {
    ...themed.errorText(isDark),
    marginBottom: 12,
  },
  errBox: {
    margin: 16,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    ...themed.errorBox(isDark),
  },
  errText: themed.errorText(isDark),
  empty: {
    paddingHorizontal: 24,
    color: colors.muted,
    fontSize: 14,
    marginBottom: 12,
  },
  group: {
    marginBottom: 20,
  },
  groupTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 10,
  },
  card: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    padding: 14,
    borderRadius: 16,
    marginBottom: 8,
  },
  cardBlock: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  cardText: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  cardDesc: {
    fontSize: 13,
    color: colors.muted,
    marginTop: 6,
  },
  cardMeta: {
    fontSize: 12,
    color: colors.muted,
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    padding: 16,
    marginBottom: 10,
  },
  rowLabel: {
    fontSize: 15,
    color: colors.text,
    fontWeight: '600',
  },
  linkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 8,
  },
  panel: {
    marginHorizontal: 16,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
  },
  subtleSurface: {
    ...themed.subtleSurface(colors, isDark),
    borderRadius: 14,
    padding: 12,
  },
  input: {
    backgroundColor: colors.input,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: colors.text,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 4,
    marginBottom: 8,
  },
}));
